---
- homebrew: name={{ item }} state=latest
  with_items:
    - vim
    - reattach-to-user-namespace

- shell: go get github.com/nsf/gocode creates={{ osx_go_gopath }}/src/github.com/nsf/gocode
  environment:
    GOPATH: "{{ osx_go_gopath | replace('~', '$HOME') }}"

- template: src=vim.zsh.j2 dest={{ zsh_custom_dir }}/vim.zsh

- template: src=vimrc.j2 dest=~/.vimrc
